#cloud-config
# This cloud-init configures the K3s master node.
# The SSH key is injected by Terraform from Google Secret Manager.
hostname: dev-k3s-master-01
manage_etc_hosts: true
ssh_authorized_keys:
  - ${user_ssh_public_key}
packages:
  - qemu-guest-agent
runcmd:
  - systemctl enable --now qemu-guest-agent
