---
- name: Install and Start Nginx
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Ensure nginx service is started and enabled on boot
      service:
        name: nginx
        state: started
        enabled: yes
