# This file is intentionally minimal.
# It defines the "what" (the Helm chart) but not the "how" (the values).
# The values will be supplied by our Kustomize overlay.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: monitoring
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.9.0 # Pinning chart version for stability
    helm:
      valueFiles:
        # This will be overridden by Kustomize to point to our specific values file.
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - ServerSideApply=true # Recommended for CRDs
